### ISSUE TITLE
After upgrade gotenv to 1.5.0, viper encounter the error

### ISSUE THREAD

**Issue by pplmx** [spf13/viper#1601]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/spf13/viper/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/spf13/viper/issues/new/choose) without success.
- [X] I have checked the [troubleshooting guide](https://github.com/spf13/viper/blob/master/TROUBLESHOOTING.md) for my problem, without success.

### Viper Version

1.16.0

### Go Version

1.21

### Config Source

Files

### Format

YAML

### Expected Behavior

Work fine.

### Actual Behavior

Not Work, throw the following error:

vendor\github.com\spf13\viper\internal\encoding\dotenv\codec.go:51:33: cannot use &buf (value of type *bytes.Buffer) as gotenv.Reader value in argument to gotenv.StrictParse: *bytes.Buffer does not implement gotenv.Reader (missing method ReadAt)

**Comment by pplmx** [comment]
maybe it's related to https://github.com/subosito/gotenv/commit/0a22e48f5e413b519abb3974224cc5302eafae35

**Comment by guybarnhartmagen** [comment]
can confirm the same issue

**Comment by subosito** [comment]
Just published `v1.6.0` to fix this issue. Please check and sorry for the noise 🙏
